import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import type { Metadata } from 'next'
import {
  Poppins,
  Lexend_Deca as LexendDeca,
  Press_Start_2P as PressStart2P,
} from 'next/font/google'
import { ToastContainer } from 'react-toastify'

import Providers from '@/Providers'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poppins',
})

const lexendDeca = LexendDeca({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lexend-deca',
})

const pressStart2P = PressStart2P({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-press-start-2p',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body
        className={`bg-neutral-900 font-sans text-neutral-400 ${poppins.variable} ${pressStart2P.variable} ${lexendDeca.variable}`}
      >
        <Providers>{children}</Providers>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  )
}
