import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import type { Metadata } from 'next'
import { Poppins, Lexend_Deca as LexendDeca } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

import Navbar from '@/components/Navbar'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poppins',
})

const lexendDeca = LexendDeca({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lexend-deca',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body className={`font-sans ${poppins.variable} ${lexendDeca.variable}`}>
        {children}
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  )
}
